version: "0.2"
ignorePaths:
  - pnpm-lock.yaml
  - package-lock.json
dictionaryDefinitions: []
dictionaries: []
words:
  - Accel
  - domi
  - Forza
  - Lovense
  - Trappy
  - vars
ignoreWords: []
import: []
