version: "0.2"
ignorePaths:
  - pnpm-lock.yaml
  - package-lock.json
dictionaryDefinitions: []
dictionaries: []
words:
  - Accel
  - Domi
  - Forza
  - Lovense
  - Trappy
  - pnpm
  - vars
ignoreWords:
  - bbwe
  - wekyb
import: []
